// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg *CreateAccountParams) (*Account, error)
	DeleteAccount(ctx context.Context, id int32) error
	GetAccount(ctx context.Context, id int32) (*Account, error)
	GetAccountForUpdate(ctx context.Context, id int32) (*Account, error)
	ListAccounts(ctx context.Context, arg *ListAccountsParams) ([]*Account, error)
	UpdateAccount(ctx context.Context, arg *UpdateAccountParams) (*Account, error)
}

var _ Querier = (*Queries)(nil)
